"""迁移脚本

Revision ID: 642fc24c4f67
Revises: df85d85d9bed
Create Date: 2026-04-07 23:37:13.084349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "642fc24c4f67"
down_revision: Union[str, None] = "df85d85d9bed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "badminton_tournament",
        sa.Column(
            "advance_count", sa.Integer(), nullable=True, comment="淘汰赛晋级总人数"
        ),
    )
    op.add_column(
        "badminton_tournament",
        sa.Column(
            "advance_top_n", sa.SmallInteger(), nullable=True, comment="每组前N名晋级"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("badminton_tournament", "advance_top_n")
    op.drop_column("badminton_tournament", "advance_count")
    # ### end Alembic commands ###
