"""迁移脚本

Revision ID: 6e6a1335f796
Revises: d98ed3570aef
Create Date: 2026-01-31 20:49:46.829479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e6a1335f796'
down_revision: Union[str, None] = 'd98ed3570aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('badminton_class_schedule', 'time_slot_id',
               existing_type=sa.SMALLINT(),
               comment='时间段ID（1-65，格式：day_index*10+slot_id，V2版本使用）',
               existing_nullable=True)
    op.alter_column('badminton_class_schedule', 'start_time',
               existing_type=postgresql.TIME(),
               comment='开始时间（V1版本使用，V2版本从配置获取）',
               existing_comment='开始时间',
               existing_nullable=True)
    op.alter_column('badminton_class_schedule', 'end_time',
               existing_type=postgresql.TIME(),
               comment='结束时间（V1版本使用，V2版本从配置获取）',
               existing_comment='结束时间',
               existing_nullable=True)
    op.alter_column('badminton_class_schedule', 'duration_minutes',
               existing_type=sa.SMALLINT(),
               comment='课时分钟数（V1版本使用，V2版本从配置获取）',
               existing_comment='课时分钟数',
               existing_nullable=True)
    op.alter_column('badminton_purchase', 'selected_time_slots',
               existing_type=sa.TEXT(),
               comment='已选上课时间段ID列表（JSON格式）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badminton_purchase', 'selected_time_slots',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='已选上课时间段ID列表（JSON格式）',
               existing_nullable=True)
    op.alter_column('badminton_class_schedule', 'duration_minutes',
               existing_type=sa.SMALLINT(),
               comment='课时分钟数',
               existing_comment='课时分钟数（V1版本使用，V2版本从配置获取）',
               existing_nullable=True)
    op.alter_column('badminton_class_schedule', 'end_time',
               existing_type=postgresql.TIME(),
               comment='结束时间',
               existing_comment='结束时间（V1版本使用，V2版本从配置获取）',
               existing_nullable=True)
    op.alter_column('badminton_class_schedule', 'start_time',
               existing_type=postgresql.TIME(),
               comment='开始时间',
               existing_comment='开始时间（V1版本使用，V2版本从配置获取）',
               existing_nullable=True)
    op.alter_column('badminton_class_schedule', 'time_slot_id',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='时间段ID（1-65，格式：day_index*10+slot_id，V2版本使用）',
               existing_nullable=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
