"""迁移脚本

Revision ID: 95a28c04c8ae
Revises: ac28c8824c05
Create Date: 2026-04-21 23:03:55.777328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '95a28c04c8ae'
down_revision: Union[str, None] = 'ac28c8824c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badminton_tournament_participant', sa.Column('current_position', sa.Integer(), nullable=True, comment='抢位赛当前位置'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badminton_tournament_participant', 'current_position')
    # ### end Alembic commands ###
