"""迁移脚本

Revision ID: e5f2a6fd70bc
Revises: 5210f9904e60
Create Date: 2026-02-01 00:26:14.362324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5f2a6fd70bc'
down_revision: Union[str, None] = '5210f9904e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('badminton_class_schedule', sa.Column('time_slot_code', sa.String(length=32), nullable=True, comment='时间段代码（A-E）'))
    op.add_column('badminton_class_schedule', sa.Column('time_slots_json', sa.Text(), nullable=True, comment='时间段JSON配置（星期+代码格式）'))
    op.alter_column('badminton_class_schedule', 'time_slot_id',
               existing_type=sa.SMALLINT(),
               comment='时间段ID（保留用于兼容）',
               existing_comment='时间段ID（1-65，格式：day_index*10+slot_id，V2版本使用）',
               existing_nullable=True)
    op.alter_column('badminton_class_schedule', 'start_time',
               existing_type=postgresql.TIME(),
               comment='开始时间',
               existing_comment='开始时间（V1版本使用，V2版本从配置获取）',
               existing_nullable=True)
    op.alter_column('badminton_class_schedule', 'end_time',
               existing_type=postgresql.TIME(),
               comment='结束时间',
               existing_comment='结束时间（V1版本使用，V2版本从配置获取）',
               existing_nullable=True)
    op.alter_column('badminton_class_schedule', 'duration_minutes',
               existing_type=sa.SMALLINT(),
               comment='课时分钟数',
               existing_comment='课时分钟数（V1版本使用，V2版本从配置获取）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badminton_class_schedule', 'duration_minutes',
               existing_type=sa.SMALLINT(),
               comment='课时分钟数（V1版本使用，V2版本从配置获取）',
               existing_comment='课时分钟数',
               existing_nullable=True)
    op.alter_column('badminton_class_schedule', 'end_time',
               existing_type=postgresql.TIME(),
               comment='结束时间（V1版本使用，V2版本从配置获取）',
               existing_comment='结束时间',
               existing_nullable=True)
    op.alter_column('badminton_class_schedule', 'start_time',
               existing_type=postgresql.TIME(),
               comment='开始时间（V1版本使用，V2版本从配置获取）',
               existing_comment='开始时间',
               existing_nullable=True)
    op.alter_column('badminton_class_schedule', 'time_slot_id',
               existing_type=sa.SMALLINT(),
               comment='时间段ID（1-65，格式：day_index*10+slot_id，V2版本使用）',
               existing_comment='时间段ID（保留用于兼容）',
               existing_nullable=True)
    op.drop_column('badminton_class_schedule', 'time_slots_json')
    op.drop_column('badminton_class_schedule', 'time_slot_code')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
