"""迁移脚本

Revision ID: f7f80e0ada53
Revises: 9f16c8b786e6
Create Date: 2026-01-26 21:25:50.246288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7f80e0ada53'
down_revision: Union[str, None] = '9f16c8b786e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('badminton_class', 'class_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'active', 'ended', name='classstatusenum'),
               nullable=False,
               existing_comment='班级状态')
    op.create_foreign_key(None, 'badminton_class', 'badminton_semester', ['semester_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('badminton_purchase', sa.Column('selected_time_slots', sa.Text(), nullable=True, comment='已选上课时间段ID列表（JSON格式）'))
    op.create_foreign_key(None, 'badminton_purchase', 'badminton_semester', ['semester_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('badminton_semester', 'status_flag',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               comment='是否启用(0:启用 1:禁用)',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'name',
               existing_type=sa.VARCHAR(length=64),
               comment='学期名称',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'semester_type',
               existing_type=postgresql.ENUM('regular', 'summer', 'winter', 'wintersummer', name='semestertypeenum'),
               comment='学期类型',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'start_date',
               existing_type=sa.DATE(),
               comment='开始日期',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'end_date',
               existing_type=sa.DATE(),
               comment='结束日期',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'week_count',
               existing_type=sa.SMALLINT(),
               server_default=None,
               comment='总周数',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'status',
               existing_type=postgresql.ENUM('planning', 'in_progress', 'active', 'completed', 'settled', 'archived', name='semesterstatusenum'),
               server_default=None,
               comment='学期状态',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'is_current',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='是否当前学期',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'settlement_date',
               existing_type=sa.DATE(),
               comment='结算日期',
               existing_nullable=True)
    op.alter_column('badminton_semester', 'carry_over_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='允许课时结转',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'max_carry_over_sessions',
               existing_type=sa.SMALLINT(),
               server_default=None,
               comment='最大结转课时数',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'description',
               existing_type=sa.TEXT(),
               comment='学期描述',
               existing_nullable=True)
    op.alter_column('badminton_semester', 'id',
               existing_type=sa.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('badminton_semester', 'uuid',
               existing_type=sa.VARCHAR(length=64),
               comment='UUID全局唯一标识',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'created_time',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'updated_time',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'created_id',
               existing_type=sa.INTEGER(),
               comment='创建人ID',
               existing_nullable=True)
    op.alter_column('badminton_semester', 'updated_id',
               existing_type=sa.INTEGER(),
               comment='更新人ID',
               existing_nullable=True)
    op.drop_constraint('badminton_semester_uuid_key', 'badminton_semester', type_='unique')
    op.drop_index('ix_badminton_semester_uuid', table_name='badminton_semester')
    op.create_index(op.f('ix_badminton_semester_uuid'), 'badminton_semester', ['uuid'], unique=True)
    op.create_index(op.f('ix_badminton_semester_created_id'), 'badminton_semester', ['created_id'], unique=False)
    op.create_index(op.f('ix_badminton_semester_updated_id'), 'badminton_semester', ['updated_id'], unique=False)
    op.alter_column('badminton_student', 'contact',
               existing_type=sa.VARCHAR(length=32),
               comment='联系人',
               existing_comment='紧急联系人',
               existing_nullable=True)
    op.alter_column('badminton_student', 'mobile',
               existing_type=sa.VARCHAR(length=20),
               comment='手机号码',
               existing_comment='紧急联系电话',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badminton_student', 'mobile',
               existing_type=sa.VARCHAR(length=20),
               comment='紧急联系电话',
               existing_comment='手机号码',
               existing_nullable=True)
    op.alter_column('badminton_student', 'contact',
               existing_type=sa.VARCHAR(length=32),
               comment='紧急联系人',
               existing_comment='联系人',
               existing_nullable=True)
    op.drop_index(op.f('ix_badminton_semester_updated_id'), table_name='badminton_semester')
    op.drop_index(op.f('ix_badminton_semester_created_id'), table_name='badminton_semester')
    op.drop_index(op.f('ix_badminton_semester_uuid'), table_name='badminton_semester')
    op.create_index('ix_badminton_semester_uuid', 'badminton_semester', ['uuid'], unique=False)
    op.create_unique_constraint('badminton_semester_uuid_key', 'badminton_semester', ['uuid'], postgresql_nulls_not_distinct=False)
    op.alter_column('badminton_semester', 'updated_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='更新人ID',
               existing_nullable=True)
    op.alter_column('badminton_semester', 'created_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('badminton_semester', 'updated_time',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'created_time',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'uuid',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='UUID全局唯一标识',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('badminton_semester', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='学期描述',
               existing_nullable=True)
    op.alter_column('badminton_semester', 'max_carry_over_sessions',
               existing_type=sa.SMALLINT(),
               server_default=sa.text('5'),
               comment=None,
               existing_comment='最大结转课时数',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'carry_over_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='允许课时结转',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'settlement_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='结算日期',
               existing_nullable=True)
    op.alter_column('badminton_semester', 'is_current',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='是否当前学期',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'status',
               existing_type=postgresql.ENUM('planning', 'in_progress', 'active', 'completed', 'settled', 'archived', name='semesterstatusenum'),
               server_default=sa.text("'planning'::semesterstatusenum"),
               comment=None,
               existing_comment='学期状态',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'week_count',
               existing_type=sa.SMALLINT(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='总周数',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='结束日期',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='开始日期',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'semester_type',
               existing_type=postgresql.ENUM('regular', 'summer', 'winter', 'wintersummer', name='semestertypeenum'),
               comment=None,
               existing_comment='学期类型',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'name',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='学期名称',
               existing_nullable=False)
    op.alter_column('badminton_semester', 'status_flag',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'0'::character varying"),
               comment=None,
               existing_comment='是否启用(0:启用 1:禁用)',
               existing_nullable=False)
    op.drop_constraint(None, 'badminton_purchase', type_='foreignkey')
    op.drop_column('badminton_purchase', 'selected_time_slots')
    op.drop_constraint(None, 'badminton_class', type_='foreignkey')
    op.alter_column('badminton_class', 'class_status',
               existing_type=sa.Enum('pending', 'active', 'ended', name='classstatusenum'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='班级状态')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
